#pragma once

namespace reindexer {
enum [[nodiscard]] SqlTokenType {
	Start = 0,
	SelectSqlToken,
	DeleteSqlToken,
	StartAfterExplain,
	SingleSelectFieldSqlToken,
	AggregationSqlToken,
	FromSqlToken,
	NamespaceSqlToken,
	SelectConditionsStart,
	NestedSelectConditionsStart,
	WhereSqlToken,
	WhereFieldSqlToken,
	NestedWhereFieldSqlToken,
	ConditionSqlToken,
	OpSqlToken,
	WhereOpSqlToken,
	FieldNameSqlToken,
	WhereFieldValueSqlToken,
	WhereFieldNegateValueSqlToken,
	NullSqlToken,
	EmptySqlToken,
	NotSqlToken,
	AndSqlToken,
	NestedAndSqlToken,
	OrSqlToken,
	BySqlToken,
	AllFieldsToken,
	SortDirectionSqlToken,
	FieldSqlToken,
	LeftSqlToken,
	InnerSqlToken,
	JoinSqlToken,
	MergeSqlToken,
	OnSqlToken,
	JoinedFieldNameSqlToken,
	ModifyConditionsStart,
	SetSqlToken,
	UpdateOptionsSqlToken,
	EqualPositionSqlToken,
	JoinTypesSqlToken,
	WhereFunction,
	ST_GeomFromTextSqlToken,
	GeomFieldSqlToken,
	StartAfterLocal,
	StartAfterLocalExplain,
	WhereFieldOrSubquerySqlToken,
	WhereFieldValueOrSubquerySqlToken,
	KnnParamsToken,
};
}
