version: "2.0"
dependencies:
  - project: Restream/reindexer
  - project: Restream/reindexer-py
    dependencies:
      - project: Restream/reindexer

default:
  build-command:
    current: echo 'default build'

build:
  - project: Restream/reindexer
    build-command:
      current: |
        sudo ./dependencies.sh
        cmake .
        make -j4
        STRIP=/bin/true cpack
  - project: Restream/reindexer-py
    build-command:
      current: echo 'build build pyrx'
