version: "2.0"
dependencies:
  - project: Restream/reindexer
  - project: Restream/reindexer-py
    dependencies:
      - project: Restream/reindexer

default:
  build-command:
    current: echo 'nothing to do'

build:
  - project: Restream/reindexer-py
    build-command:
      current: |
        python3 setup.py build
        sudo python3 setup.py install
        ./.github/workflows/test.sh
