name: build

on: push
jobs:
  build-windows-2019:
    runs-on: windows-2019
    strategy:
      matrix:
        compiler: ["Visual Studio 16 2019"]
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build Reindexer
        run: |
          mkdir build && cd build
          cmake -G "${{matrix.compiler}}" -DBUILD_ANN_INDEXES=none ..
          cmake --build . --config Release
          cmake --build . --config Release --target face
          cmake --build . --config Release --target swagger
          cpack

